# Run a CI test every time we merge in a pull request.
branches:
  only:
    - master

# Test both in-source and out-of-source builds, as well as mildly optimized vs
# wildly optimized.
env:
  - BUILD_TYPE=in_source
  - BUILD_TYPE=out_of_source
  - BUILD_TYPE=hella_optimized

language: c
script: .travis/test.sh
addons:
  apt:
    packages:
      - valgrind
